### ISSUE TITLE
Blocker: Saving/loading audio files to mongodb

### ISSUE THREAD

**Issue by graigjanssen** [graigjanssen/sample-jam#1]
Successfully deployed to Heroku, so now the main goal is to save and retrieve user's audio samples from mongo.  I went down [this](http://stackoverflow.com/questions/18555771/how-to-insert-a-blob-into-mongodb-in-meteor) path found on stackoverflow.  Succeeded in making an object that seemed to contain an array of binary data, but got an error: 413 payload too large when attempting to post to db with ajax.  I have tried sending shorter and shorter audio clips but same error.  

Definitely more research to be done, but wanted to put this up in case anyone can steer me in the right direction.  Thanks!

**Comment by amadden80** [comment]
This is a problem you will hit!!!!    Unfortunately, audio files are not small data.  This MIGHT work if you send up only split second clips... but... who wants that?!  

We will likely need to use a different file uploading procedure here.  I was hoping that wouldn't be the case... but looks like it is.

There are ways of sending up files one part at a time.  This is the path I would suggest.   I always need to look this kind of thing up every time.  

Does, https://www.npmjs.com/package/express-fileupload look possible?  
Can you spike on that for a minute?  I am going to look at it more now too.

**Comment by graigjanssen** [comment]
Just saw your response, thanks!  Will check that npm file uploader out
now.  Have been searching and reading for a while now but have been feeling
increasingly lost on this issue.  Seemed like GridFS might be the way to go
even if my files are under 16mb, but so far am very unclear on how to even
get started implementing GridFS.

On Tue, Feb 16, 2016 at 10:57 AM, Andrew notifications@github.com wrote:

> This is a problem you will hit!!!! Unfortunately, audio files are not
> small data. This MIGHT work if you send up only split second clips...
> but... who wants that?!
> 
> We will likely need to use a different file uploading procedure here. I
> was hoping that wouldn't be the case... but looks like it is.
> 
> There are ways of sending up files one part at a time. This is the path I
> would suggest. I always need to look this kind of thing up every time.
> 
> Does, https://www.npmjs.com/package/express-fileupload look possible?
> 
> Can you spike on that for a minute? I am going to look at it more now too.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/graigjanssen/sample-jam/issues/1#issuecomment-184743979
> .

## 

_Graig Janssen_
(856)-685-9008
www.graigjanssen.com
